import type { Artifact, AuditEvent, CanonicalRepresentation, EvidencePack, FormulaGraphState, LineageEdge, PivotMetadata, Publication, StyleMetadata, TransformationResult, WorkbookPackage } from "@rasid/contracts";
import { z } from "zod";
export declare const ExcelStoreManifestSchema: z.ZodObject<{
    manifest_id: z.ZodString;
    store_root: z.ZodString;
    workbook_state_path: z.ZodString;
    workbook_versions_path: z.ZodString;
    publications_path: z.ZodString;
    artifacts_path: z.ZodString;
    evidence_path: z.ZodString;
    audit_path: z.ZodString;
    lineage_path: z.ZodString;
    charts_path: z.ZodString;
    exported_workbook_path: z.ZodNullable<z.ZodString>;
    publication_backend_ref: z.ZodNullable<z.ZodString>;
    backend_service_ref: z.ZodNullable<z.ZodString>;
    backend_service_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    service_manifest_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    backend_manifest_path: z.ZodNullable<z.ZodString>;
    backend_manifest_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    backend_object_manifest_path: z.ZodNullable<z.ZodString>;
    backend_object_manifest_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    backend_download_url: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    manifest_id: string;
    store_root: string;
    workbook_state_path: string;
    workbook_versions_path: string;
    publications_path: string;
    artifacts_path: string;
    evidence_path: string;
    audit_path: string;
    lineage_path: string;
    charts_path: string;
    exported_workbook_path: string | null;
    publication_backend_ref: string | null;
    backend_service_ref: string | null;
    backend_service_url: string | null;
    service_manifest_url: string | null;
    backend_manifest_path: string | null;
    backend_manifest_url: string | null;
    backend_object_manifest_path: string | null;
    backend_object_manifest_url: string | null;
    backend_download_url: string | null;
    updated_at: string;
}, {
    manifest_id: string;
    store_root: string;
    workbook_state_path: string;
    workbook_versions_path: string;
    publications_path: string;
    artifacts_path: string;
    evidence_path: string;
    audit_path: string;
    lineage_path: string;
    charts_path: string;
    exported_workbook_path: string | null;
    publication_backend_ref: string | null;
    backend_service_ref: string | null;
    backend_manifest_path: string | null;
    backend_object_manifest_path: string | null;
    updated_at: string;
    backend_service_url?: string | null | undefined;
    service_manifest_url?: string | null | undefined;
    backend_manifest_url?: string | null | undefined;
    backend_object_manifest_url?: string | null | undefined;
    backend_download_url?: string | null | undefined;
}>;
export type ExcelStoreManifest = z.infer<typeof ExcelStoreManifestSchema>;
export type ExcelStoreBundle = {
    workbookId: string;
    workbookPackage: WorkbookPackage;
    canonicalRepresentation: CanonicalRepresentation;
    formulaGraph: FormulaGraphState;
    analysis: unknown;
    transformationResults: TransformationResult[];
    pivotMetadata: PivotMetadata[];
    pivotCaches: unknown[];
    styleMetadata: StyleMetadata[];
    lambdaRegistry: unknown[];
    chartHistory: unknown[];
    mappingPreviews: unknown[];
    generatedCharts: unknown[];
    nativeWorkbookObjects: unknown;
    sourceMetadata: unknown;
    artifacts: Artifact[];
    evidencePack: EvidencePack;
    auditEvents: AuditEvent[];
    lineageEdges: LineageEdge[];
    publication: Publication | null;
    exportedWorkbookPath: string | null;
    chartPaths: string[];
};
export declare const defaultExcelEngineStorageRoot: (root?: string) => string;
export declare const defaultExcelEngineBackendRoot: (root?: string) => string;
export declare class ExcelEngineStore {
    readonly rootDir: string;
    readonly backendRootDir: string;
    constructor(rootDir?: string, backendRootDir?: string);
    private workbookRoot;
    private backendPublicationRoot;
    private backendObjectRoot;
    private backendServiceRoot;
    persistBundle(bundle: ExcelStoreBundle): ExcelStoreManifest;
}
