/**
 * Default Themes, Slide Masters, and Layout Templates
 * E02-0031, E02-0032, E02-0044
 */

import type { Theme, SlideMaster, SlideLayoutType } from '../types';

// ============================================================
// DEFAULT THEMES
// ============================================================

export const defaultThemes: Theme[] = [
  {
    id: 'royal-sovereignty',
    name: 'Royal Sovereignty',
    nameAr: 'السيادة الملكية',
    colors: {
      primary: '#1a237e',
      secondary: '#283593',
      accent: '#c9a84c',
      text: '#1a1a2e',
      textSecondary: '#64748b',
      background: '#ffffff',
      surface: '#f8fafc',
      border: '#e2e8f0',
      success: '#16a34a',
      warning: '#d97706',
      error: '#dc2626',
    },
    fonts: {
      titleFamily: 'Tajawal',
      bodyFamily: 'Tajawal',
      headingFamily: 'Tajawal',
      monoFamily: 'IBM Plex Mono Arabic',
      titleWeight: 'bold',
      bodyWeight: 'regular',
      headingWeight: 'semibold',
      titleSize: 36,
      headingSize: 24,
      bodySize: 16,
      captionSize: 12,
    },
    slideBackground: {
      type: 'solid',
      color: '#ffffff',
    },
    elementDefaults: {
      borderRadius: 8,
      padding: 16,
      shadow: { x: 0, y: 2, blur: 8, spread: 0, color: 'rgba(0,0,0,0.08)' },
    },
    direction: 'rtl',
    category: 'corporate',
  },
  {
    id: 'midnight-gold',
    name: 'Midnight Gold',
    nameAr: 'ذهب منتصف الليل',
    colors: {
      primary: '#c9a84c',
      secondary: '#1e293b',
      accent: '#f59e0b',
      text: '#f1f5f9',
      textSecondary: '#94a3b8',
      background: '#0f172a',
      surface: '#1e293b',
      border: '#334155',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    fonts: {
      titleFamily: 'Tajawal',
      bodyFamily: 'Tajawal',
      headingFamily: 'Tajawal',
      monoFamily: 'IBM Plex Mono Arabic',
      titleWeight: 'bold',
      bodyWeight: 'regular',
      headingWeight: 'semibold',
      titleSize: 36,
      headingSize: 24,
      bodySize: 16,
      captionSize: 12,
    },
    slideBackground: {
      type: 'solid',
      color: '#0f172a',
    },
    elementDefaults: {
      borderRadius: 8,
      padding: 16,
      shadow: { x: 0, y: 2, blur: 12, spread: 0, color: 'rgba(201,168,76,0.1)' },
    },
    direction: 'rtl',
    category: 'elegant',
  },
  {
    id: 'clean-minimal',
    name: 'Clean Minimal',
    nameAr: 'نظيف بسيط',
    colors: {
      primary: '#18181b',
      secondary: '#3f3f46',
      accent: '#2563eb',
      text: '#18181b',
      textSecondary: '#71717a',
      background: '#fafafa',
      surface: '#ffffff',
      border: '#e4e4e7',
      success: '#16a34a',
      warning: '#ca8a04',
      error: '#dc2626',
    },
    fonts: {
      titleFamily: 'Tajawal',
      bodyFamily: 'Tajawal',
      headingFamily: 'Tajawal',
      monoFamily: 'monospace',
      titleWeight: 'bold',
      bodyWeight: 'regular',
      headingWeight: 'medium',
      titleSize: 40,
      headingSize: 28,
      bodySize: 16,
      captionSize: 12,
    },
    slideBackground: {
      type: 'solid',
      color: '#fafafa',
    },
    elementDefaults: {
      borderRadius: 4,
      padding: 20,
    },
    direction: 'rtl',
    category: 'minimal',
  },
  {
    id: 'saudi-green',
    name: 'Saudi Green',
    nameAr: 'الأخضر السعودي',
    colors: {
      primary: '#006c35',
      secondary: '#004d25',
      accent: '#c9a84c',
      text: '#1a1a1a',
      textSecondary: '#6b7280',
      background: '#ffffff',
      surface: '#f0fdf4',
      border: '#bbf7d0',
      success: '#16a34a',
      warning: '#d97706',
      error: '#dc2626',
    },
    fonts: {
      titleFamily: 'Tajawal',
      bodyFamily: 'Tajawal',
      headingFamily: 'Tajawal',
      monoFamily: 'monospace',
      titleWeight: 'bold',
      bodyWeight: 'regular',
      headingWeight: 'semibold',
      titleSize: 36,
      headingSize: 24,
      bodySize: 16,
      captionSize: 12,
    },
    slideBackground: {
      type: 'solid',
      color: '#ffffff',
    },
    elementDefaults: {
      borderRadius: 8,
      padding: 16,
    },
    direction: 'rtl',
    category: 'corporate',
  },
  {
    id: 'tech-gradient',
    name: 'Tech Gradient',
    nameAr: 'تدرج تقني',
    colors: {
      primary: '#6366f1',
      secondary: '#8b5cf6',
      accent: '#06b6d4',
      text: '#f8fafc',
      textSecondary: '#cbd5e1',
      background: '#0c0a1a',
      surface: '#1a1830',
      border: '#312e5c',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
    },
    fonts: {
      titleFamily: 'Tajawal',
      bodyFamily: 'Tajawal',
      headingFamily: 'Tajawal',
      monoFamily: 'monospace',
      titleWeight: 'extrabold',
      bodyWeight: 'regular',
      headingWeight: 'bold',
      titleSize: 40,
      headingSize: 26,
      bodySize: 16,
      captionSize: 12,
    },
    slideBackground: {
      type: 'gradient',
      gradient: {
        type: 'linear',
        angle: 135,
        stops: [
          { color: '#0c0a1a', position: 0 },
          { color: '#1a1830', position: 50 },
          { color: '#0f172a', position: 100 },
        ],
      },
    },
    elementDefaults: {
      borderRadius: 12,
      padding: 16,
      shadow: { x: 0, y: 4, blur: 20, spread: 0, color: 'rgba(99,102,241,0.15)' },
    },
    direction: 'rtl',
    category: 'tech',
  },
  {
    id: 'arabic-classic',
    name: 'Arabic Classic',
    nameAr: 'كلاسيكي عربي',
    colors: {
      primary: '#7c2d12',
      secondary: '#92400e',
      accent: '#c9a84c',
      text: '#1c1917',
      textSecondary: '#78716c',
      background: '#fef7ed',
      surface: '#fff7ed',
      border: '#fed7aa',
      success: '#16a34a',
      warning: '#d97706',
      error: '#dc2626',
    },
    fonts: {
      titleFamily: 'Tajawal',
      bodyFamily: 'Tajawal',
      headingFamily: 'Tajawal',
      monoFamily: 'monospace',
      titleWeight: 'bold',
      bodyWeight: 'regular',
      headingWeight: 'semibold',
      titleSize: 36,
      headingSize: 24,
      bodySize: 16,
      captionSize: 12,
    },
    slideBackground: {
      type: 'solid',
      color: '#fef7ed',
    },
    elementDefaults: {
      borderRadius: 4,
      padding: 16,
    },
    direction: 'rtl',
    category: 'arabic-classic',
  },
];

// ============================================================
// DEFAULT SLIDE MASTERS
// ============================================================

export const defaultMasters: SlideMaster[] = [
  {
    id: 'master-title',
    name: 'Title Slide',
    nameAr: 'شريحة العنوان',
    layoutType: 'title',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 10, y: 25 }, size: { width: 80, height: 25 }, label: 'العنوان الرئيسي' },
      { id: 'ph-subtitle', type: 'text', position: { x: 15, y: 55 }, size: { width: 70, height: 12 }, label: 'العنوان الفرعي' },
    ],
  },
  {
    id: 'master-title-content',
    name: 'Title + Content',
    nameAr: 'عنوان ومحتوى',
    layoutType: 'title-content',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 5, y: 5 }, size: { width: 90, height: 12 }, label: 'العنوان' },
      { id: 'ph-body', type: 'text', position: { x: 5, y: 20 }, size: { width: 90, height: 72 }, label: 'المحتوى' },
    ],
  },
  {
    id: 'master-two-column',
    name: 'Two Columns',
    nameAr: 'عمودان',
    layoutType: 'two-column',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 5, y: 5 }, size: { width: 90, height: 12 }, label: 'العنوان' },
      { id: 'ph-left', type: 'text', position: { x: 5, y: 20 }, size: { width: 43, height: 72 }, label: 'العمود الأيمن' },
      { id: 'ph-right', type: 'text', position: { x: 52, y: 20 }, size: { width: 43, height: 72 }, label: 'العمود الأيسر' },
    ],
  },
  {
    id: 'master-image-right',
    name: 'Image Right',
    nameAr: 'صورة يسار',
    layoutType: 'image-right',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 5, y: 5 }, size: { width: 45, height: 12 }, label: 'العنوان' },
      { id: 'ph-body', type: 'text', position: { x: 5, y: 20 }, size: { width: 45, height: 72 }, label: 'المحتوى' },
      { id: 'ph-image', type: 'image', position: { x: 55, y: 5 }, size: { width: 40, height: 87 }, label: 'الصورة' },
    ],
  },
  {
    id: 'master-image-left',
    name: 'Image Left',
    nameAr: 'صورة يمين',
    layoutType: 'image-left',
    placeholders: [
      { id: 'ph-image', type: 'image', position: { x: 5, y: 5 }, size: { width: 40, height: 87 }, label: 'الصورة' },
      { id: 'ph-title', type: 'text', position: { x: 50, y: 5 }, size: { width: 45, height: 12 }, label: 'العنوان' },
      { id: 'ph-body', type: 'text', position: { x: 50, y: 20 }, size: { width: 45, height: 72 }, label: 'المحتوى' },
    ],
  },
  {
    id: 'master-full-image',
    name: 'Full Image',
    nameAr: 'صورة كاملة',
    layoutType: 'full-image',
    placeholders: [
      { id: 'ph-image', type: 'image', position: { x: 0, y: 0 }, size: { width: 100, height: 100 }, label: 'الصورة' },
      { id: 'ph-title', type: 'text', position: { x: 10, y: 70 }, size: { width: 80, height: 15 }, label: 'العنوان' },
    ],
  },
  {
    id: 'master-chart-focus',
    name: 'Chart Focus',
    nameAr: 'تركيز على المخطط',
    layoutType: 'chart-focus',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 5, y: 5 }, size: { width: 90, height: 10 }, label: 'العنوان' },
      { id: 'ph-chart', type: 'chart', position: { x: 5, y: 18 }, size: { width: 90, height: 75 }, label: 'المخطط' },
    ],
  },
  {
    id: 'master-kpi',
    name: 'KPI Dashboard',
    nameAr: 'مؤشرات أداء',
    layoutType: 'kpi',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 5, y: 5 }, size: { width: 90, height: 10 }, label: 'العنوان' },
      { id: 'ph-kpi1', type: 'text', position: { x: 5, y: 20 }, size: { width: 28, height: 35 }, label: 'مؤشر 1' },
      { id: 'ph-kpi2', type: 'text', position: { x: 36, y: 20 }, size: { width: 28, height: 35 }, label: 'مؤشر 2' },
      { id: 'ph-kpi3', type: 'text', position: { x: 67, y: 20 }, size: { width: 28, height: 35 }, label: 'مؤشر 3' },
      { id: 'ph-body', type: 'text', position: { x: 5, y: 60 }, size: { width: 90, height: 32 }, label: 'التفاصيل' },
    ],
  },
  {
    id: 'master-comparison',
    name: 'Comparison',
    nameAr: 'مقارنة',
    layoutType: 'comparison',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 5, y: 5 }, size: { width: 90, height: 10 }, label: 'العنوان' },
      { id: 'ph-left', type: 'text', position: { x: 5, y: 18 }, size: { width: 43, height: 75 }, label: 'الجانب الأول' },
      { id: 'ph-right', type: 'text', position: { x: 52, y: 18 }, size: { width: 43, height: 75 }, label: 'الجانب الثاني' },
    ],
  },
  {
    id: 'master-blank',
    name: 'Blank',
    nameAr: 'فارغة',
    layoutType: 'blank',
    placeholders: [],
  },
  {
    id: 'master-section-header',
    name: 'Section Header',
    nameAr: 'رأس القسم',
    layoutType: 'section-header',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 10, y: 35 }, size: { width: 80, height: 20 }, label: 'عنوان القسم' },
      { id: 'ph-subtitle', type: 'text', position: { x: 15, y: 58 }, size: { width: 70, height: 10 }, label: 'وصف القسم' },
    ],
  },
  {
    id: 'master-thank-you',
    name: 'Thank You',
    nameAr: 'شكراً لكم',
    layoutType: 'thank-you',
    placeholders: [
      { id: 'ph-title', type: 'text', position: { x: 10, y: 30 }, size: { width: 80, height: 25 }, label: 'شكراً لكم' },
      { id: 'ph-contact', type: 'text', position: { x: 20, y: 60 }, size: { width: 60, height: 15 }, label: 'معلومات التواصل' },
    ],
  },
];

// ============================================================
// LAYOUT DISPLAY NAMES
// ============================================================

export const layoutNames: Record<SlideLayoutType, { en: string; ar: string }> = {
  'title': { en: 'Title Slide', ar: 'شريحة العنوان' },
  'title-content': { en: 'Title + Content', ar: 'عنوان ومحتوى' },
  'two-column': { en: 'Two Columns', ar: 'عمودان' },
  'three-column': { en: 'Three Columns', ar: 'ثلاثة أعمدة' },
  'image-left': { en: 'Image Left', ar: 'صورة يمين' },
  'image-right': { en: 'Image Right', ar: 'صورة يسار' },
  'full-image': { en: 'Full Image', ar: 'صورة كاملة' },
  'blank': { en: 'Blank', ar: 'فارغة' },
  'comparison': { en: 'Comparison', ar: 'مقارنة' },
  'timeline': { en: 'Timeline', ar: 'خط زمني' },
  'kpi': { en: 'KPI Dashboard', ar: 'مؤشرات أداء' },
  'chart-focus': { en: 'Chart Focus', ar: 'تركيز على المخطط' },
  'infographic': { en: 'Infographic', ar: 'إنفوجرافيك' },
  'quote': { en: 'Quote', ar: 'اقتباس' },
  'section-header': { en: 'Section Header', ar: 'رأس القسم' },
  'agenda': { en: 'Agenda', ar: 'جدول الأعمال' },
  'conclusion': { en: 'Conclusion', ar: 'الخلاصة' },
  'thank-you': { en: 'Thank You', ar: 'شكراً لكم' },
  'team': { en: 'Team', ar: 'الفريق' },
  'process': { en: 'Process', ar: 'العملية' },
};
